name: Build
on:
  push:
    branches:
    - '**'
    paths-ignore:
    - .github/workflows/**
    - '**.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display Author
        run: |
          echo "Hello!, Run triggered by ${{ github.actor }}"
